### ISSUE TITLE
research spike for how to get conditional render to switch between our current page views

### ISSUE THREAD

**Issue by elizhahn** [Afoucheaux/rancid_tomatillos#11]

**Comment by Afoucheaux** [comment]
https://reactjs.org/docs/lifting-state-up.html
Looks like state is private meaning that it can only be passed down as props and not pass up the chain. The React Doc recommend lifting state up to the closest shared ancestor. This lead me to think that the way we talked about last night may be the best way forward. (putting the single movie data in state on the App component). This leads me to wonder if we should also lift the full movie lists state up there also.
